# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('image', models.FileField(max_length=1000, upload_to='movie_posters/')),
            ],
        ),
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_value', models.CharField(blank=True, max_length=10)),
                ('issuing_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuing_user', to=settings.AUTH_USER_MODEL)),
                ('trusted_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trusted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='0', max_length=100)),
                ('corresponding_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Movie')),
            ],
        ),
    ]
