# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movielens_id',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
